### PR TITLE
Fixing windows test

### PR DESCRIPTION
**Pull request by hannahci**

### CODE REVIEW

**Comment by simonpf** [comment]
Can you fix the formatting? :)

**Comment by hannahci** [comment]
> Can you fix the formatting? :)

Did that! I think it was not related to my changes, but now it should be ok

**Comment by hannahci** [comment]
> > Can you fix the formatting? :)
> 
> Did that! I think it was not related to my changes, but now it should be ok

Well.. Those are strange errors happening now! Don't think it's connected to my pushes.. right?

**Comment by hannahci** [comment]
Ah, I need to add the sys package to the test-ones so that it can run I guess. I'll do that later!

**Comment by hannahci** [comment]
Ok, I don't understand why the tests fail now. Looks like something is wrong with setup.py?

**Pull request merged**
