### PR TITLE
Package definition and documentation

### PR DESCRIPTION
**Pull request by hannahci**

### CODE REVIEW

**Comment by hannahci** [comment]
Sorry for a bit messy commit-history here. Only check the files changes, not the commits (or disregard these:
- Adding workflow to run tests on push - bb46c87
- Adding install and test-badge - 9d67fb7
- Fixing the pipeline - 562d265
- Merge pull request #1 from hannahci/ci - d246f2a
- Revert "Merge pull request #1 from hannahci/ci" - 1470f67
)

**Comment by simonpf** [comment]
Very nice!

**Comment by hannahci** [comment]
so ok to merge? ;)

**Comment by hannahci** [comment]
I can't merge it because I don't have the permissions

**Pull request merged**
